language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
# command to install dependencies
install:
  # - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest
